### ISSUE TITLE
Add validation to Playground as the backendConfig's resource requests should not be greater than limits

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#135]
**What would you like to be cleaned**:

Make sure the resources are qualified. 
https://github.com/InftyAI/llmaz/blob/8637aa93cad2bc7a3636655b426ab4f818077671/api/inference/v1alpha1/config_types.go#L48-L52

**Why is this needed**:

**Comment by googs1025** [comment]
i will try to fix this in these day
/assign

**Comment by googs1025** [comment]
I want to confirm one thing: how do we ensure resource eligibility validation? For example: limit > request?

**Comment by googs1025** [comment]
> I want to confirm one thing: how do we ensure resource eligibility validation? For example: limit >= request?

Apologies, I didn't see the title clearly. The title already indicates it.😓
