### ISSUE TITLE
Support HA with LeaderElection 

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#23]
We only have one replica for controller right now.

**Comment by qinguoyi** [comment]
https://github.com/InftyAI/llmaz/blob/b6141a4d32172f2f6500afdd483958c5407797c6/cmd/main.go#L77-L94


hi, from the code point of view, LeaderElection is currently supported to support HA. Are there any other requirements? would you mean to add more replica nums?

**Comment by kerthcet** [comment]
Thanks @qinguoyi for pointing it out, that's true. Then what we left is just make it configurable with helm chart, as well as the **Replicas** of the controller, here's the values.yaml: https://github.com/InftyAI/llmaz/blob/main/chart/values.global.yaml

Would you like to finish the work? That would be really appreciate, I think it wouldn't take a lot of time.

**Comment by qinguoyi** [comment]
> Thanks @qinguoyi for pointing it out, that's true. Then what we left is just make it configurable with helm chart, as well as the **Replicas** of the controller, here's the values.yaml: https://github.com/InftyAI/llmaz/blob/main/chart/values.global.yaml
> 
> Would you like to finish the work? That would be really appreciate, I think it wouldn't take a lot of time.

tks, i push a PR here,https://github.com/InftyAI/llmaz/pull/168

**Comment by kerthcet** [comment]
Solved by #168 

/close
